In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
sess = tf.InteractiveSession()

min = -5.
max = 5.

logits = np.random.rand(2,3,3) * (max-min) + min
print(logits)
logits = tf.constant(logits)

y = np.random.randint(0,2,(2,3,3)) * 1.
print(y)

sig = tf.nn.sigmoid(logits)
loss = tf.nn.sigmoid_cross_entropy_with_logits(labels=y, logits=logits)
mloss = tf.reduce_mean(loss)
mloss2 = tf.losses.sigmoid_cross_entropy(y, logits)
s, l, m, m2 = sess.run([sig, loss, mloss, mloss2])
print("sigmoid:")
print(s)
print("loss:")
print(l)
print("mean loss:")
print(m)
print("mean loss 2:")
print(m2)

In [1]:
sess = tf.InteractiveSession()

min = -5.
max = 5.

logits = np.random.rand(3,3) * (max-min) + min
print(logits)
logits = tf.constant(logits)

y = np.random.randint(0,2,(3,3)) * 1.
print(y)

# Weights test
w = np.zeros((3,3))
w[y==1] = 4.
w[y==0] = 1.
print(w)
w = tf.constant(w)

sig = tf.nn.sigmoid(logits)
loss = tf.nn.sigmoid_cross_entropy_with_logits(labels=y, logits=logits)
mloss = tf.reduce_mean(loss)

loss_w = tf.multiply(loss, w)
mloss_w = tf.reduce_mean(loss_w)

mloss2 = tf.losses.sigmoid_cross_entropy(y, logits, weights=w)
s, l, lw, m, mw, m2 = sess.run([sig, loss, loss_w, mloss, mloss_w, mloss2])
print("sigmoid:")
print(s)
print("loss:")
print(l)
print("weighted loss:")
print(lw)
print("mean loss:")
print(m)
print("weighted mean loss:")
print(mw)
print("mean loss 2 (weighted):")
print(m2)

/home/jfaath/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


[[-3.09414181  1.43347691  0.74173967]
 [-3.3623769   3.52241053  1.24788428]
 [-3.80567144 -4.38149981 -4.93982211]]
[[ 1.  1.  0.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 4.  4.  1.]
 [ 4.  4.  4.]
 [ 4.  4.  4.]]
sigmoid:
[[ 0.04334955  0.80744248  0.67737616]
 [ 0.0334922   0.97131873  0.77693341]
 [ 0.02176022  0.0123521   0.00710503]]
loss:
[[ 3.13845901  0.21388346  1.13126821]
 [ 3.3964428   0.02910061  0.25240064]
 [ 3.8276719   4.39392884  4.9469525 ]]
weighted loss:
[[ 12.55383605   0.85553383   1.13126821]
 [ 13.58577121   0.11640244   1.00960256]
 [ 15.3106876   17.57571536  19.78780999]]
mean loss:
2.37001199644
weighted mean loss:
9.10295858349
mean loss 2 (weighted):
9.1029586792


In [2]:
sess = tf.InteractiveSession()

min = -5.
max = 5.

logits = np.random.rand(2,3,3) * (max-min) + min
print(logits)
logits = tf.constant(logits)

y = np.random.randint(0,2,(2,3,3)) * 1.
print(y)

# Weights test
w = np.zeros((2,3,3))
w[y==1] = 4.
w[y==0] = 1.
print(w)
w = tf.constant(w)

sig = tf.nn.sigmoid(logits)
loss = tf.nn.sigmoid_cross_entropy_with_logits(labels=y, logits=logits)
mloss = tf.reduce_mean(loss)

loss_w = tf.multiply(loss, w)
mloss_w = tf.reduce_mean(loss_w)

mloss2 = tf.losses.sigmoid_cross_entropy(y, logits, weights=w)
s, l, lw, m, mw, m2 = sess.run([sig, loss, loss_w, mloss, mloss_w, mloss2])
print("sigmoid:")
print(s)
print("loss:")
print(l)
print("weighted loss:")
print(lw)
print("mean loss:")
print(m)
print("weighted mean loss:")
print(mw)
print("mean loss 2 (weighted):")
print(m2)

[[[-4.13267305  0.76963473  2.57117856]
  [ 2.73659315 -4.70256182  0.66529762]
  [-0.21819704  3.93789097 -4.45578147]]

 [[ 0.11267678 -3.34991641  3.79092978]
  [-3.95597889 -2.21458549  2.02023501]
  [ 1.90709677  0.08554618  3.33858222]]]
[[[ 1.  1.  0.]
  [ 0.  1.  1.]
  [ 0.  0.  0.]]

 [[ 1.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]]
[[[ 4.  4.  1.]
  [ 1.  4.  4.]
  [ 1.  1.  1.]]

 [[ 4.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]]
sigmoid:
[[[ 0.01578673  0.68344187  0.92898349]
  [ 0.9391517   0.00899045  0.66044942]
  [ 0.44566614  0.9808833   0.01147797]]

 [[ 0.52813943  0.0338979   0.97792376]
  [ 0.01878047  0.09844833  0.88290531]
  [ 0.87069263  0.52137351  0.96572895]]]
loss:
[[[ 4.14858572  0.38061367  2.64484287]
  [ 2.79937141  4.71159293  0.41483474]
  [ 0.58998814  3.95719276  0.01154435]]

 [[ 0.63839496  0.03448576  3.81325334]
  [ 0.01895906  0.10363792  2.14477233]
  [ 2.04556302  0.73683476  3.3734543 ]]]
weighted loss:
[[[  1.65943429e+01   1.52245468e+00  